spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/security
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  security:
    jwt:
      secret: ${JWT_SECRET}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql